name: Build and Release mfup

on:
  push:
    tags:
      - 'v*'   

permissions:
  contents: write  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp InquirerPy pyinstaller

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile --clean --noconfirm --name mfup coremfup/mfup/cli.py

      - name: Package artifact (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir upload
          tar -czvf upload/mfup-${{ github.ref_name }}-linux.tar.gz -C dist mfup

      - name: Package artifact (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir upload
          tar -czvf upload/mfup-${{ github.ref_name }}-macos.tar.gz -C dist mfup

      - name: Package artifact (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir upload
          powershell Compress-Archive -Path dist/mfup.exe -DestinationPath upload/mfup-${{ github.ref_name }}-windows.zip

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
